name: Terraform Apply

on:
  push:
    branches: [ main ]
 

jobs:
  terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./terraform
    env:  
          TF_VAR_service_account_name: ${{secrets.SERVICE_ACCOUNT_NAME}}
          TF_VAR_project_id: ${{secrets.PROJECT_ID}}
          TF_VAR_project_name: ${{secrets.PROJECT_NAME}}
          TF_VAR_service_token: "./key.json"
          # general vars
          TF_VAR_region: ${{secrets.REGION}}
          TF_VAR_zone: ${{secrets.ZONE}}
    steps:
      - uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: |
          echo ${{secrets.SERVICE_TOKEN}} >> './key.json'
          terraform apply --auto-approve
  push:
    needs: terraform
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Download gcloud tools
        run: |
          sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
          curl https://packages.cloud.google.com/apt/doc/apt-key.gpg
          sudo tee /usr/share/keyrings/cloud.google.gpg
          sudo snap install google-cloud-cli --classic
      - name: Authorize gcloud util
        run: |
          echo ${{secrets.SERVICE_TOKEN}} >> './key.json'
          gcloud auth activate-service-account ${{secrets.SERVICE_ACCOUNT_NAME}} --key-file="./key.json"
     
      - name: Push files to gcp bucket
        run: |
          gsutil rsync -r ./${{secrets.TEMPLATE}}/ gs://${{secrets.PROJECT_NAME}}
          gsutil defacl set public-read gs://${{secrets.PROJECT_NAME}}

          
        