name: Terraform Apply

on:
  push:
    branches: [ main ]

jobs:
  terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./terraform
        
    steps:
      - uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve
        with:
          client_id: ${{secrets.CLIENT_ID}}
          client_secret: ${{secrets.CLIENT_SECRET}}
          subscription_id: ${{secrets.SUBSCRIPTION_ID}}
          tenant_id: ${{secrets.TENANT_ID}}

          # general vars
          project: ${{secrets.PROJECT}}
          environment: ${{secrets.ENVIRONMENT}}
          location: ${{secrets.LOCATION}}